### ISSUE TITLE
Panic: EOF

### ISSUE THREAD

**Issue by arohner** [scoutapp/docker-scout#2]
Running docker-scout on CoreOS. Everything started fine, and then 12 hours later:

```
Sep 30 21:03:50 ip-10-0-4-53.ec2.internal bash[1739]: scoutd: 2015/09/30 21:03:50 Logging to /var/log/scout/scoutd.log
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: panic: EOF
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 35 [running]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: runtime.panic(0x72dce0, 0xc208038020)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/runtime/panic.c:279 +0xf5
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: github.com/scoutapp/pusher.(*Connection).poll(0xc208283170)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/pusher/connection.go:54 +0xb5
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by github.com/scoutapp/pusher.New
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/pusher/connection.go:35 +0x2e2
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 16 [semacquire, 871 minutes]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: sync.runtime_Semacquire(0xc208288ec8)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /tmp/makerelease290705518/go/src/pkg/runtime/sema.goc:199 +0x30
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: sync.(*WaitGroup).Wait(0xc20828fec0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/sync/waitgroup.go:129 +0x14b
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: main.startDaemon()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:94 +0x265
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: main.main()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:55 +0x4f5
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 19 [finalizer wait]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: runtime.park(0x4189e0, 0x9a3f58, 0x9a21a9)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/runtime/proc.c:1369 +0x89
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: runtime.parkunlock(0x9a3f58, 0x9a21a9)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/runtime/proc.c:1385 +0x3b
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: runfinq()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/runtime/mgc0.c:2644 +0xcf
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: runtime.goexit()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/runtime/proc.c:1445
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 20 [syscall, 874 minutes]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: os/signal.loop()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by os/signal.init·1
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/os/signal/signal_unix.go:27 +0x32
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 21 [chan receive, 874 minutes]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: main.signalHandler(0xc208028000)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:330 +0x4f
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by main.main
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:45 +0x29c
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 28 [IO wait]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.runtime_pollWait(0x7ff9569ed960, 0x72, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /tmp/makerelease290705518/go/src/pkg/runtime/netpoll.goc:146 +0x66
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.(*pollDesc).Wait(0xc2081c2ae0, 0x72, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.(*pollDesc).WaitRead(0xc2081c2ae0, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.(*netFD).accept(0xc2081c2a80, 0x861688, 0x0, 0x7ff9569ec418, 0xb)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/fd_unix.go:419 +0x343
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.(*TCPListener).AcceptTCP(0xc20803c038, 0x47f433, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net/http.tcpKeepAliveListener.Accept(0xc20803c038, 0x0, 0x0, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/http/server.go:1947 +0x4b
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net/http.(*Server).Serve(0xc2080053e0, 0x7ff9569f67e8, 0xc20803c038, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/http/server.go:1698 +0x91
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net/http.(*Server).ListenAndServe(0xc2080053e0, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/http/server.go:1688 +0x14d
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net/http.ListenAndServe(0x7bdb10, 0xe, 0x0, 0x0, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/net/http/server.go:1778 +0x79
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: main.initPayloadEndpoint()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:117 +0x64
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by main.startDaemon
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:90 +0x211
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 17 [syscall, 874 minutes]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: runtime.goexit()
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/go1.3.3/go/src/pkg/runtime/proc.c:1445
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 34 [chan receive]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: github.com/scoutapp/pusher.(*Connection).pong(0xc208283170)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/pusher/connection.go:44 +0xaf
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by github.com/scoutapp/pusher.New
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/pusher/connection.go:34 +0x2ca
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 31 [select]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: github.com/scoutapp/scoutd/collectors.(*StatsdCollector).aggregate(0xc208260680)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/collectors/statsd.go:82 +0x77f
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by github.com/scoutapp/scoutd/collectors.(*StatsdCollector).Start
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/collectors/statsd.go:64 +0x43
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 29 [sleep]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: time.Sleep(0x6fc23ac00)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /tmp/makerelease290705518/go/src/pkg/runtime/time.goc:39 +0x31
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: main.initPusher(0xc208288ec0, 0xc20828fec0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:142 +0x1f7
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by main.startDaemon
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:91 +0x233
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 30 [chan receive]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: main.reportLoop(0xc208288ec0, 0xc20828fec0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:189 +0x166
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: created by main.startDaemon
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /opt/scoutd_go_workspace/src/github.com/scoutapp/scoutd/scoutd.go:92 +0x255
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: goroutine 33 [IO wait, 871 minutes]:
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.runtime_pollWait(0x7ff9569ed8b0, 0x72, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: /tmp/makerelease290705518/go/src/pkg/runtime/netpoll.goc:146 +0x66
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal bash[1739]: net.(*pollDesc).Wait(0xc2081c2e60, 0x72, 0x0, 0x0)
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal systemd[1]: scout.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal systemd[1]: scout.service: Unit entered failed state.
Oct 01 11:38:12 ip-10-0-4-53.ec2.internal systemd[1]: scout.service: Failed with result 'exit-code'.
```

**Comment by arohner** [comment]
Hrm, I just realized this might be an issue with scoutd, not docker-scout. LMK if this issue would be more appropriate in another project.

**Comment by itsderek23** [comment]
@arohner,

Sorry for the issues here - it looks like an issue w/a web socket connection. 

Just to confirm: did the agent stop running after the crash? The agent process was not restarted?

**Comment by arohner** [comment]
Correct, the process died. I've since added:

`Restart=on-failure`

to my scout.service fleet unit file

**Comment by itsderek23** [comment]
Apologies again @arohner - we'll check this out. 

/cc @dlanderson

**Comment by dlanderson** [comment]
Sorry for that @arohner - I've added "--restart=always" to the "docker run" command in the readme which will ensure docker restarts the container if scoutd exits.
